import Head from 'next/head'
import Image from 'next/image'
import Footer from '../Components/Footer'
import Header from '../Components/Header'
import Main from '../Components/Main'
import styles from '../styles/Home.module.css'
import React,{createContext,useState,useEffect} from 'react'
import { CounterContext } from '../Components/CounterContext'
import { SumContext } from '../Components/SumContext'
import useLocalStorage from '../CustomHooks/useLocalStorage';


//let init;
let sumInit;
if (typeof window !== 'undefined') {
  // Perform localStorage action
//init=localStorage?.getItem("counter")?localStorage?.getItem("counter"):0;
sumInit=localStorage?.getItem("sum")?localStorage?.getItem("sum"):0;

}


export default function Home() {
useEffect(() => {
  
  
  
  setCounter(counterLocal?counterLocal:0)
   setSum(sumInit)
 
 
}, [])


  
  const [counterLocal,setCounterLocal]=useLocalStorage("counter")
  const [counter, setCounter] = useState("");
  const [sum, setSum] = useState("")

  
return(
 
    <CounterContext.Provider value={[counter,setCounter]}>
     <SumContext.Provider value={[sum,setSum]}>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
   

    <Main/>
    
    
    <Footer/>
     
    </div>
    </SumContext.Provider>
    </CounterContext.Provider>
 
  )
}
